fixtures:
  repositories:
    'concat_native': 'git://github.com/theforeman/puppet-concat.git'
    'dns': 'git://github.com/theforeman/puppet-dns.git'
    'inifile': 'git://github.com/puppetlabs/puppetlabs-inifile.git'
    'keystone': 'git://github.com/stackforge/puppet-keystone.git'
    'mysql': 'git://github.com/puppetlabs/puppetlabs-mysql.git'
    'openstacklib': 'git://github.com/stackforge/puppet-openstacklib.git'
    'stdlib': 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
    'powerdns': 'git://github.com/antonlindstrom/puppet-powerdns.git'
    'vcsrepo': 'git://github.com/puppetlabs/puppetlabs-vcsrepo'
    'python': 'git://github.com/stankevich/puppet-python.git'
  symlinks:
    'designate': "#{source_dir}"
